= Test

eXo Platform is delivered as a zip bundle, built on every commit, and available in our https://repository.exoplatform.org/[maven repository] 
and in our http://acceptance.exoplatform.org/[acceptance platform].

If you want to test the zip bundle with one of the supported databases, you can find more information in https://community.exoplatform.org[eXo Tribe site].

== Databases

eXo Platform uses by default an HSQLDB database.
eXo Platform supports several RDBMS databases, each of them in multiple versions.

First, setup eXo to connect to your database following the https://docs.exoplatform.org/en/latest/database_configuration.html[eXo documentation].
Then start the database.

=== MySQL

You should use a docker container from https://hub.docker.com/_/mysql/[Docker hub].
For example this command starts a MySQL database server exposed on the default port (3306) and creates a database `plf` :

[source,shell]
----
docker run -d --name mysql-5.7.22 -p 3306:3306 -e MYSQL_ROOT_PASSWORD=plf -e MYSQL_DATABASE=plf mysql:5.7.22
----

You can connect from your eXo instance with the user `root` and the password `plf`.
Please refer to the https://hub.docker.com/_/mysql/[Docker hub page] for full details and configuration options.

=== PostgreSQL

There is no specific Docker image for PostgreSQL for eXo, you should use the official image from https://hub.docker.com/_/postgres/[Docker hub].
For example this command starts a PostgreSQL 9.6.6 database server exposed on the default port (5432) and creates a database `plf` :

[source,shell]
----
docker run -d --name postgres-9.6.6 -p 5432:5432 -e POSTGRES_PASSWORD=plf -e POSTGRES_DB=plf postgres:9.6.6
----

You can connect from your eXo instance with the user `postgres` and the password `plf`.
Please refer to the https://hub.docker.com/_/postgres/[Docker hub page] for full details and configuration options.