= Translations

All the translations are managed in https://crowdin.com[Crowdin].
For each PLF version, a Crowdin project is created and linked.
A synchronization between the eXo source code and Crowdin is performed once per day.

== How to add / delete a new localization file?

In root path of each project (ecms, wallet, calendar...), you 'll find a `translation.properties` file where
we reference the `MASTER localization file` for each localization file. (in general we reference the _en.properties
or _en.xml in translation.properties to make sure that english language is considered as `MASTER localization
language` for Crowdin)

Each line in `translation.properties` must be formatted as follows:

where

* *crowdin-path* is the path of the localization file in Crowdin relative to the root of the Crowdin project
* *source-path* is the path of the english (en) localization file in the project sources, relative to the value of the property "baseDir"

For example:

[source,shell]
----
baseDir=platform/calendar/
webapp/CalendarPortlet.properties=calendar-webapp/src/main/resources/locale/portlet/calendar/CalendarPortlet_en.properties
----

So if you developed a new application that references a new localization file, you will have to add its reference in root
file `translation.properties` to make sure that it's translated by Crowdin contributors, else it will be ignored.

== How to update an existing translation string?

Updating a string must be done in Crowdin directly (if it is done in the source code, it will be reset by the next synchronization).
Once validated the translated string will be pushed in the sources during the next synchronization.

== How to add a new translation string in an existing localization file?

In order to add a new string, simply add it in the master localization file (the file that you added in translation.properties).
The master localization file is the file without a language suffix if it exists, for example `resources.properties`.
Otherwise it is the english version, for example `resources_en.properties`.
It will automatically be added in Crowdin during the next synchronization.
You can add the string in others localization files, for testing purpose, but it will be reset during the next synchronization.

== How to delete a translation string?

Deleting a string must be done in the sources by simply removing the string in all the localization files containing this string.
The string will be automatically deleted in Crowdin during the next synchronization.
