= Contributions

== Workflow

The contribution workflow mainly relies on Github Pull Requests. 

=== Creating the PR

Once a contribution is ready to be shared, commit the changes (see <<id-commits-messages-best-practices>> for Commits best practices) and create a PR.
Creating a PR is easy and allows to share, discuss and validate more easily the contribution.
To create a PR :

* create a branch locally with your fix and push it to Github

* go to Github, and select your branch, to create New pull request

* select the right base branch (`develop`, `feature/`, `stable/`...) and check that the PR contains *only your commits*

* fill the description !

* click on *Create pull request*

* choose one or multiple reviewer(s)

* add in task the reference to the PR in a comment

* wait for a review and the build of the PR to commit changes on target branch

=== Reviewing the PR

When a PR is submitted, it has to be reviewed by at least one peer.

Please refer to the chapter <<id-contributions-reviews>> to learn more about review best practices.

During the review iterations, the developer may have to update the contribution. In order to update a PR, just push a new commit in the same branch, no need to create a new branch and a new PR.
Creating a new PR for each update prevents from following easily the discussion and the updates history.

WARNING: `Code Review does NOT mean Test, Reviewers are NOT Testers` +
The role of the reviewers is to review the code changes (code best practices, better/easier solution, ...).
They do not necessarily have to test (they can if they want/need of course).
The author of the PR must not rely on the reviewers to test it, he/she is responsible for that (and the QA people will help during their test campaigns).

=== Automatic checks on PR

Besides reviews by peer, all PR are submitted to the following automatic checks:

* *compilation* - Each time a PR is submitted or updated, the project is compiled. If the compilation fails, the PR is automatically rejected.
* *unit tests* - Each time a PR is submitted or updated, the unit tests are executed. If at least one test fails, the PR is automatically rejected.
* *minimum test coverage* - Each time a PR is submitted or updated, a check is done on test coverage to make sure it does not decrease (see <<id-test-coverage>> for more details). If the new test coverage is lower than the one set in the Maven configuration, the PR is automatically rejected.

=== Merging the PR

When the PR has been validated by the peer and has passed all the automatic checks, the PR can be merged in the target branch. Before merging the PR in the target branch, make sure the branch of the PR is up to date.

== Community Contributions

Anyone with a Github account can contribute to eXo Platform.
The only difference for people outside of the eXo Platform organization is they must sign a link:../resources/sources/eXo_Platform_ContributorAgreement_EN_v1.4.pdf[Contribution License Agreement].
The Contributor License Agreement is needed to clarify the terms of usage of contributions by eXo Platform and the entire open source community.

The CLA must be printed, signed, then scanned as a PDF file and sent at cla@exoplatform.com.

== Commits messages best practices

It is often important to browse the source code history to understand when and why a change has been done. Good commits message are therefore crucial to help developers in maintaining a code base. In order to improve the quality of the commit messages, the following rules must be respected:

* use 
+
[source,shell]
----
git commit 
----
+
instead of 
+
[source,shell]
----
git commit -m “My commit message” 
----
when committing a change, in order to write a more detailed commit message and use the commit template

* the commit message must start with a line containing a short subject (max 100 characters) which starts by the Task issue number and then describes briefly what the commit does. For example : TASK-40308 Allow to update kudos message in activity stream
* the commit subject must not be a copy/paste of the Task issue summary. As said previously, it must describe what the commit does, as if the sentence would start with “If applied, this commit will …​”.
* after the subject, one blank line must be added before starting the body
* the body describes in details what the commit does and must answer 2 questions : why is this change needed and how does this change address the issue. It should give as much information as possible to make it easy for another developer who does not know deeply the context to understand the commit. Therefore the body is never too long.
* after the body, a list of links to relevant resources can be added (optional). It must be separated from the body by one blank line.

Here is an example of commit message following these rules:

[source,shell]
----
TASK-37899 Enhance extension registry to trigger event when extensions updated

When updating extensionRegistry asynchronously from different modules, the other modules should be triggered for this update to allow retrieving newly registered extensions. This way, the extension points in all portlets will can be aware, when listening to adequate event, of any change in extensionRegistry.
----

Of course, all commit messages do not need to be that long, but it must contain all relevant information to understand what and why the changes have been done.

In order to help developers, a template is available (https://gist.github.com/lisawolderiksen/a7b99d94c92c6671181611be1641c733[How to apply it] ).

*Template*

[source,shell]
----
# TASK-<task-id>: (If applied, this commit will...) <subject>
# |<----  Using a Maximum Of 100 Characters  ---->|

# Why is this change needed?
# Prior to this change, ...
# How does it address the issue?
# This change ...
# |<----   Try To Limit Each Line to a Maximum Of 72 Characters   ---->|

# Provide links or keys to any relevant tickets, articles or other resources

# --------------------
# Remember to
#    Capitalize the subject line
#    Use the imperative mood in the subject line
#    Do not end the subject line with a period
#    Separate subject from body with a blank line
#    Use the body to explain what and why vs. how
#    Can use multiple lines with "-" for bullet points in body
# --------------------
----

== Pull Requests best practices

As well as good commits messages are important for code base maintainers, good PRs descriptions are important for reviewers. It helps to understand what the developer has done and why. The PR title must start with the Task issue, then describe briefly what the PR does. For example : _TASK-40308 Allow to update kudos message in activity stream_

The PR description must at least provide the information given in the commit message body : why is this change needed and how does this change address the issue (Tip: using the first line of the commit message as the PR title and the commit message body as the PR description is a good start for the PR description).

It can also give the following information when relevant:

* Alternative solutions tried and why they failed
* Any question, remark or doubt that the developer has
* Tested environments (tomcat/jboss, databases, ldap, browsers, addons, …)
* Links to resources which can help to understand the contribution

The PR does not need to describe the issue (functional impacts, reproduction steps, …​) since it is already done in the related Task issue.

== Contributions reviews

=== How to do a review ?

The reviewers must use the review feature of Github to do the review. On the first comment, the button “Start review” must be used. Then, once the review is done, the developer must submit the review by clicking on the button “Review changes”, then select the right option:

* `Comment` : the review contains only remarks or questions which ask for clarifications but do not necessarily ask for changes

* `Approve` : the PR is approved

* `Request changes` : the review contains at least a comment asking for a change in the PR

If the option `Approve` is selected, the PR is validated, and the Task issue status must be changed to Merge . If the option `Comment` or `Request changes` is selected, the PR is considered as not validated.

=== What should I care when reviewing a Pull Request ?

When reviewing a Pull Request, the following things must be checked:

* Correctness of the fix/feature
* Learning
* Coding best practices
* Unit Tests
* Security
* Performance
* Maintainability
* Troubleshooting
* Upgrades
* API breaking
* Code formatting (if not yet automated)
* Documentation

WARNING: This list does not only apply to reviewers, but also to contributors!