= Git - Settings

== GitHub

GitHub is the platform we chose to host our Git repositories.
*To contribute to eXo projects you have to create a https://www.github.com/[GitHub] account.*

For eXo employees it is recommended to create one with the same username as the one provided by the company (GoogleApp Id) when you joined us.
*You have to commit using your exoplatform.com email by setting it in your global git configuration or locally into each eXo repository clone* (see below).

To retrieve your rights to push changes or to pull private repositories you have to register your github account into your profile in our internal IDM https://my.exoplatform.org[My eXo].

GitHub provides a lot of http://help.github.com/[documentation] and especially an installation/configuration guide for each operating system :

* http://help.github.com/linux-set-up-git/[Linux]
* http://help.github.com/win-set-up-git/[Windows]
* http://help.github.com/mac-set-up-git/[MacOS]

Please follow these guides to setup your environment.

== Git Configuration

It is recommended to create an SSH private key (with a password) and to use it to access to your Git(Hub) repositories (see Github guides above).

By default you have at least to setup your default identity that will be used for all git instances on the system if you don't override them locally.

[source,shell]
----
$ git config –global user.name "John Doe"
$ git config –global user.email "jdoe@exoplatform.com"
----

We recommend also :

* to configure git to activate use colors if you terminal supports it :

[source,shell]
----
$ git config color.ui true
----

* to configure git to push only the current branch by default to avoid to send to the server some changes in others branches you weren't ready to share

[source,shell]
----
$ git config –global push.default current
----

* to setup line endings preferences for Unix/Mac users

[source,shell]
----
$ git config –global core.autocrlf input
$ git config –global core.safecrlf true
----

* to setup line endings preferences for Windows users

[source,shell]
----
$ git config –global core.autocrlf true
$ git config –global core.safecrlf true
----

* to reduce the number of files to consider when performing rename detection during a merge. The merge is working pretty well on small repositories (with move and rename of files). But it's not working on large repositories as the detection of file renaming is O(n²), so we need to update some threshold (more explanations are available in this post : http://blogs.atlassian.com/2011/10/confluence_git_rename_merge_oh_my/[http://blogs.atlassian.com/2011/10/confluence_git_rename_merge_oh_my/]) :

[source,shell]
----
 git config –global merge.renameLimit 10000
----

* to configure git to add some command aliases to easily call them with `git &lt;ALIAS_NAME&gt;`.
You just add a section `[alias]` in your `~/.gitconfig` file with entries like bellow

[source,shell]
----
\[alias]

\[source]
\----
##### Basic aliases
# Long status
st = status
# Short status
s = status -s
# Show all branches
br = branch -a
# Show branches with commit message
sb = show-branch
# Commit
ci = commit
# Checkout
co = checkout
# Show remote repositories
r  = remote -v
# Amend last commit
amend = ci --amend
# Removes files/directories from staging
unadd = rm -r --cached

##### Diff aliases
# Diff and show commands with word-diff style
wd = diff --word-diff
ws = show --word-diff
# Show diff before pull
do = diff ORIG_HEAD HEAD
# Show modified lines in the index
staged = diff --cached
# Show modified files
changes= diff --name-status -r
# Diff with statistics
ds = diff --stat -r

##### Log aliases
# Show HEAD commit
head = log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative -n1
# Short one line logs with ref-names
l  = log --oneline --decorate=short
# Shows the last git logentry (hash, author, date commitmessage)
llm = log -1
# Short one line logs with ref-names and statistics
gl = log --oneline --decorate --stat --graph
# Short one line logs with ref-names (yellow, date (green) and author (blue)
glog = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
# Show last commit
lc = log ORIG_HEAD.. --stat --no-merges
# Graph log with full commit message
glaaa = log --graph --abbrev-commit --date=relative

##### Misc
# Show last commiter
whois = !sh -c 'git log -i -1 --pretty=\"format:%an <%ae>\n\" --author=\"$1\"' -
# Show last commit message
whatis = show -s --pretty='tformat:%h (%s, %ad)' --date=short
# Hash of HEAD
h = rev-list --max-count=1 HEAD
# Show users which have commits in current branch
ul = !git log --format='%aN' | sort -u
# Number of commits in current branch
c  = !git log --oneline | wc -l
# Creates a tar.gz archive named after the last commits hash from HEAD! in the directory above the repository
ahg = !git archive HEAD --format=tar | gzip > ../`git h`.tar.gz
# shows ignored directories
ignored = !git ls-files --others -i --exclude-standard --directory
# Move to the root of the repository
root = !cd $(git rev-parse --show-cdup)
# Show the root directory of the repository
sroot = rev-parse --show-toplevel
# Prune remote branches
prune-all = !git remote | xargs -n 1 git remote prune
# Show aliases
aliases = !git config --get-regexp 'alias.*' | colrm 1 6 | sed 's/[ ]/ = /'
# Show upstream for the current branch
upstream = !git for-each-ref --format='%(upstream:short)' `git symbolic-ref HEAD`
\----

----

== Git & IDEs

Git is natively supported by all IDE :

* Eclipse : http://www.eclipse.org/egit/[EGit plugin] bundled by default in the major part of eclipse distributions.
* IntelliJ : http://www.jetbrains.com/idea/webhelp/using-git-integration.html[Native]
* Netbeans : http://netbeans.org/projects/versioncontrol/pages/Git_main[Native since 7.1]